# Generated by Django 3.2 on 2021-05-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=200)),
                ('training_content', models.TextField()),
                ('training_schedule', models.DateTimeField(verbose_name='training schedule')),
            ],
        ),
    ]
